name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACTION_TOKEN }}
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Make Gradlew executable
      run: chmod +x gradlew
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: Deploy to diligentp.com
      uses: appleboy/ssh-action@master
      env:
        ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
      with:
        host: diligentp.com
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}  # Secrets에 저장된 SSH 패스워드 사용
        script: |
          # deploy.sh 스크립트를 로컬에 저장
          deploy_sh_url="https://raw.githubusercontent.com/belogstudy/belog-springboot/main/.github/workflows/deploy.sh"
          curl -sSL $deploy_sh_url -o deploy.sh
  
          # deploy.sh 스크립트 실행
          bash deploy.sh $ACTION_TOKEN
          
          # deploy.sh 실행 후 스크립트를 삭제
          rm deploy.sh
